"""
Pydantic v2 Data Models for the AegisSwarm Attack Execution Engine.
"""

from uuid import UUID, uuid4
from datetime import datetime, timezone
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field
from core.schema import AttackRecord


class ExecutionRequest(BaseModel):
    """
    Input request specifying an AttackRecord and target LLM provider execution settings.
    """
    attack_record: AttackRecord = Field(..., description="Canonical AttackRecord to execute.")
    provider: str = Field(..., description="Target LLM provider identifier (e.g. 'openai', 'ollama').")
    model: Optional[str] = Field(default=None, description="Optional target model override.")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0, description="Sampling temperature.")
    top_p: float = Field(default=1.0, ge=0.0, le=1.0, description="Nucleus sampling top-p.")
    max_tokens: Optional[int] = Field(default=None, ge=1, description="Maximum tokens to generate.")
    seed: Optional[int] = Field(default=None, description="Random seed.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary execution metadata.")


class ExecutionResult(BaseModel):
    """
    Complete output result of executing an AttackRecord against an LLM provider.
    """
    execution_id: UUID = Field(default_factory=uuid4, description="Unique execution UUID.")
    session_id: UUID = Field(..., description="Execution session UUID.")
    attack_id: UUID = Field(..., description="Sample ID of the source AttackRecord.")
    provider: str = Field(..., description="Provider name executed.")
    model: str = Field(..., description="Model name executed.")
    completion: str = Field(..., description="Completion text generated by target model.")
    finish_reason: str = Field(default="stop", description="Generation finish reason.")
    attack_success: Optional[bool] = Field(default=None, description="Optional evaluator attack success flag.")
    latency_ms: float = Field(default=0.0, ge=0.0, description="API round-trip latency in ms.")
    started_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC execution start timestamp."
    )
    completed_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC execution completion timestamp."
    )
    duration_ms: float = Field(default=0.0, ge=0.0, description="Total execution duration in ms.")
    prompt_tokens: int = Field(default=0, ge=0, description="Prompt token count.")
    completion_tokens: int = Field(default=0, ge=0, description="Completion token count.")
    total_tokens: int = Field(default=0, ge=0, description="Total token count.")
    estimated_cost: float = Field(default=0.0, ge=0.0, description="Estimated execution cost in USD.")
    retry_count: int = Field(default=0, ge=0, description="Number of retries executed.")
    status: str = Field(default="completed", description="Execution status: 'completed', 'failed', or 'timed_out'.")
    raw_provider_metadata: Dict[str, Any] = Field(default_factory=dict, description="Raw metadata returned by provider.")
