"""
Strategy definitions and recommendation models for AegisSwarm Adaptive Swarm Intelligence.
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class StrategyType(str, Enum):
    """Supported attack mutation strategy types."""
    DIRECT_OVERRIDE = "direct_override"
    ROLEPLAY_WRAPPER = "roleplay_wrapper"
    XML_DELIMITER_ESCAPE = "xml_delimiter_escape"
    BASE64_OBFUSCATION = "base64_obfuscation"
    HYPOTHETICAL_FRAMING = "hypothetical_framing"
    SUFFIX_ATTACK = "suffix_attack"


class StrategyRecommendation(BaseModel):
    """
    Pydantic v2 data model representing a recommended attack strategy generated by AdaptiveIntelligence.
    """
    strategy_id: str = Field(..., description="Unique identifier for the strategy.")
    strategy_type: StrategyType = Field(..., description="Classification type of strategy.")
    recommended_agent: str = Field(..., description="Target swarm agent recommended to execute this strategy.")
    confidence_score: float = Field(default=0.8, ge=0.0, le=1.0, description="Confidence score for this recommendation.")
    rationale: str = Field(default="", description="Detailed rationale based on prior evaluator findings.")
    suggested_mutations: List[str] = Field(default_factory=list, description="List of proposed mutation techniques.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary strategy metadata.")
