"""
Pydantic v2 Data Models for AegisSwarm Semantic Reasoning Engine.
"""

from uuid import UUID, uuid4
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class SimilarityMatch(BaseModel):
    """Semantic similarity match result against historical learning memory."""
    record_id: str = Field(...)
    attack_id: str = Field(...)
    dataset: str = Field(default="unknown")
    provider: str = Field(...)
    model: str = Field(...)
    taxonomy_node: str = Field(...)
    similarity_score: float = Field(..., ge=0.0, le=1.0)
    matched_features: List[str] = Field(default_factory=list)


class ProviderRecommendation(BaseModel):
    """Recommendation for optimal LLM target provider selection."""
    recommended_provider: str = Field(...)
    recommended_model: str = Field(...)
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    estimated_latency_ms: float = Field(default=50.0)
    estimated_cost_usd: float = Field(default=0.001)
    rationale: str = Field(...)


class MutationPlan(BaseModel):
    """Chain of mutation strategy transformations (e.g. Persona -> Markdown -> Roleplay -> Delimiter -> Recursive Wrapper)."""
    plan_id: UUID = Field(default_factory=uuid4)
    chain: List[str] = Field(default_factory=lambda: ["persona", "markdown", "roleplay", "delimiter", "recursive"])
    target_prompt: str = Field(...)
    expected_evasion_rate: float = Field(default=0.85, ge=0.0, le=1.0)


class StrategyCandidate(BaseModel):
    """Strategy candidate generated by StrategyGenerator (minimum 5 candidates per reasoning pass)."""
    candidate_id: UUID = Field(default_factory=uuid4)
    attack_family: str = Field(...)
    mutation_family: str = Field(...)
    provider: str = Field(...)
    model: str = Field(default="gpt-4o")
    estimated_cost: float = Field(default=0.002, ge=0.0)
    estimated_latency_ms: float = Field(default=45.0, ge=0.0)
    estimated_success: float = Field(default=0.80, ge=0.0, le=1.0)
    estimated_severity: str = Field(default="High")
    estimated_confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    reasoning_text: str = Field(...)
    rank_score: Optional[float] = Field(default=None)


class CritiqueResult(BaseModel):
    """Critique engine evaluation of a generated strategy candidate."""
    candidate_id: UUID = Field(...)
    novelty_score: float = Field(..., ge=0.0, le=1.0)
    expected_success_score: float = Field(..., ge=0.0, le=1.0)
    cost_efficiency_score: float = Field(..., ge=0.0, le=1.0)
    risk_score: float = Field(..., ge=0.0, le=1.0)
    complexity_score: float = Field(..., ge=0.0, le=1.0)
    overall_critique_score: float = Field(..., ge=0.0, le=1.0)
    critique_notes: str = Field(...)


class ReflectionResult(BaseModel):
    """Post-execution reflection analysis outcome."""
    reflection_id: UUID = Field(default_factory=uuid4)
    campaign_id: Optional[str] = Field(default=None)
    attack_id: Optional[str] = Field(default=None)
    what_worked: str = Field(...)
    what_failed: str = Field(...)
    why_outcome: str = Field(...)
    how_to_improve: str = Field(...)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ReasoningTimeline(BaseModel):
    """Timeline entry tracking reasoning steps."""
    step_name: str = Field(...)
    duration_ms: float = Field(default=0.0)
    details: Dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ReasoningRequest(BaseModel):
    """Request payload initiating an autonomous reasoning and strategic planning pass."""
    request_id: UUID = Field(default_factory=uuid4)
    objective: str = Field(...)
    target_provider: str = Field(default="openai")
    target_model: str = Field(default="gpt-4o")
    taxonomy_node: str = Field(default="AUAO-PI-DIR-DEL-XML")
    budget_usd: float = Field(default=10.0, ge=0.0)
    max_candidates: int = Field(default=5, ge=5)


class ReasoningResponse(BaseModel):
    """Response payload containing generated candidates, critique, reflection, recommendation, and final plan."""
    request_id: UUID = Field(...)
    chosen_strategy: StrategyCandidate = Field(...)
    all_candidates: List[StrategyCandidate] = Field(default_factory=list)
    similarity_matches: List[SimilarityMatch] = Field(default_factory=list)
    provider_recommendation: ProviderRecommendation = Field(...)
    mutation_plan: MutationPlan = Field(...)
    critiques: List[CritiqueResult] = Field(default_factory=list)
    reflections: List[ReflectionResult] = Field(default_factory=list)
    timeline: List[ReasoningTimeline] = Field(default_factory=list)
    overall_confidence: float = Field(..., ge=0.0, le=1.0)


class ReasoningMemoryRecord(BaseModel):
    """Record stored in ReasoningMemory."""
    record_id: UUID = Field(default_factory=uuid4)
    request_id: str = Field(...)
    objective: str = Field(...)
    chosen_strategy_id: str = Field(...)
    overall_confidence: float = Field(...)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class ReasoningStatistics(BaseModel):
    """Summary statistics for reasoning engine performance."""
    total_plans: int = Field(default=0)
    avg_candidates_per_pass: float = Field(default=5.0)
    avg_confidence: float = Field(default=0.85)
    top_provider_recommendation: str = Field(default="openai")
